### ISSUE TITLE
Missing notes in Entity Framework - Code First

### ISSUE THREAD

**Issue by nbrownlee2** [DMIT-2018/StudentNotes#27]
In the Notes section of Entity Framework - Code First there is missing or TBA sections for the attributes section. We have been assigned the take home exercise for EF-Code First however, to refer to the notes to completely understand the attributes will be hard to do.  Please finish this sooner than later for our take home exercise. Thanks so much :)

**Comment by dgilleland** [comment]
Actually, you will find the Code Demos most helpful for the [assignment](http://dmit-2018.github.io/evaluations/evaluations/EntityFramework/exercise.html). The Notes section is thinner, but the Code Demos are more complete. See

* [ORM with Entity Framework](http://dmit-2018.github.io/demos/docs/demos/eRestaurant/entityFramework/demo/demo.html)
* [Entity Framework Practice Solution](http://dmit-2018.github.io/demos/docs/demos/eRestaurant/entityFramework/practice/practice-solution.html)
